import Link from "next/link";
import { Check, ExternalLink, MessageCircle, Sparkles } from "lucide-react";
import type { LocaleCode } from "@/lib/locale";
import type { HindiPage } from "@/data/hindi-pages";
import { uiCopy } from "@/data/locale-ui";
import { Button } from "./ui/button";

export function HindiPageTemplate({ content, locale }: { content: HindiPage; locale: LocaleCode }) {
  const copy = uiCopy[locale];
  return <main>
    <section className="brand-gradient temple-silhouette pattern-mandala relative overflow-hidden px-4 py-20 text-white sm:px-6 lg:px-8 lg:py-28"><div className="relative mx-auto max-w-7xl"><p className="inline-flex items-center gap-2 rounded-full border border-gold/40 bg-black/15 px-4 py-2 text-xs font-bold text-gold"><Sparkles className="h-4 w-4" />{content.eyebrow}</p><h1 className="mt-6 max-w-4xl font-serif text-5xl font-semibold leading-[1.08] sm:text-6xl lg:text-7xl">{content.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-orange-50/85">{content.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href={`/${locale}/plan-my-trip`}>{copy.planTrip}</Link></Button><Button asChild variant="outline" size="lg"><a href={`https://wa.me/?text=${encodeURIComponent(`${content.title}: https://indiankumbh.com/${locale}`)}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4" />{copy.share}</a></Button></div></div></section>
    <section className="pattern-mandala bg-cream px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_340px]"><div className="space-y-6">{content.sections.map((section, index) => <article key={section.title} className="premium-card rounded-3xl border p-7 sm:p-9"><span className="text-xs font-bold tracking-widest text-saffron">0{index + 1}</span><h2 className="mt-3 font-serif text-3xl font-semibold text-ink">{section.title}</h2><p className="mt-4 text-base leading-8 text-stone-600">{section.text}</p>{section.bullets && <ul className="mt-5 grid gap-3 sm:grid-cols-2">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-2 rounded-xl bg-white/70 p-3 text-sm leading-6 text-stone-700"><Check className="mt-1 h-4 w-4 shrink-0 text-saffron" />{bullet}</li>)}</ul>}</article>)}</div><aside className="space-y-6 lg:sticky lg:top-28 lg:self-start"><div className="rounded-3xl border border-gold/35 bg-sand p-7"><h2 className="font-serif text-2xl font-semibold text-ink">{copy.keepInMind}</h2><ul className="mt-5 space-y-4">{content.tips.map((tip) => <li key={tip} className="flex gap-3 text-sm leading-6 text-stone-700"><Check className="mt-0.5 h-5 w-5 shrink-0 text-saffron" />{tip}</li>)}</ul></div><a href="https://www.google.com/maps/dir/?api=1&destination=Ujjain%2C%20Madhya%20Pradesh" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-3xl bg-ink p-6 font-bold text-white transition hover:bg-maroon">{copy.openMaps}<ExternalLink className="h-5 w-5" /></a></aside></div></section>
    <section className="bg-white px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-6 rounded-[2rem] bg-maroon p-8 text-center text-white sm:p-12 md:flex-row md:text-left"><div><p className="text-sm font-bold uppercase tracking-widest text-gold">{copy.customize}</p><h2 className="mt-2 font-serif text-3xl font-semibold">{copy.personalPlan}</h2></div><Button asChild size="lg"><Link href={`/${locale}/plan-my-trip`}>{copy.startPlanning}</Link></Button></div></section>
  </main>;
}
