from __future__ import annotations


VERIFIED_NSE_MAPPINGS: list[dict[str, str]] = [
    {"name": "Apsis Aerocom", "symbol": "APSISAERO", "segment": "NSE SME", "legal_name": "Apsis Aerocom Limited"},
    {"name": "Teja Engineering Industries", "symbol": "TEJA", "segment": "NSE SME"},
    {"name": "Avana Electrosystems", "symbol": "AVANA", "segment": "NSE SME"},
    {"name": "Omnitech Engineering", "symbol": "OMNI", "segment": "NSE"},
    {"name": "Vivid Electromech", "symbol": "VIVIDEL", "segment": "NSE SME"},
    {"name": "SEDEMAC Mechatronics", "symbol": "SEDEMAC", "segment": "NSE"},
    {
        "name": "OnEMI Technology Solutions (KISSHT)",
        "symbol": "KISSHT",
        "segment": "NSE",
        "legal_name": "OnEMI Technology Solutions Limited",
    },
    {"name": "RFBL Flexi Pack", "symbol": "RFBL", "segment": "NSE SME"},
    {"name": "KRM Ayurveda", "symbol": "KRMAYURVED", "segment": "NSE SME"},
    {"name": "Teamtech Formwork Solutions", "symbol": "TEAMTECH", "segment": "NSE SME"},
    {"name": "Gaudium IVF", "symbol": "GAUDIUMIVF", "segment": "NSE SME"},
    {"name": "Grover Jewells", "symbol": "GJL", "segment": "NSE SME"},
    {"name": "Amagi Media Labs", "symbol": "AMAGI", "segment": "NSE"},
    {"name": "Shadowfax Technologies", "symbol": "SHADOWFAX", "segment": "NSE"},
    {"name": "GSP Crop Science", "symbol": "GSPCROP", "segment": "NSE"},
    {"name": "Shreedhar Spinners", "symbol": "SHREEDHAR", "segment": "NSE SME"},
    {"name": "E to E Transportation Infrastructur...", "symbol": "E2ERAIL", "segment": "NSE SME"},
    {"name": "IC Electricals Company", "symbol": "ICELCO", "segment": "NSE SME"},
    {"name": "Bharat Coking Coal", "symbol": "BHARATCOAL", "segment": "NSE"},
    {"name": "Q-Line Biotech", "symbol": "QLINE", "segment": "NSE SME"},
    {"name": "Central Mine Planning & Design Inst...", "symbol": "CMPDI", "segment": "NSE"},
    {"name": "Sai Parenteral's", "symbol": "SAIPARENT", "segment": "NSE SME"},
    {"name": "Powerica", "symbol": "POWERICA", "segment": "NSE"},
    {"name": "Mobilise App Lab", "symbol": "MOBILISE", "segment": "NSE SME"},
    {"name": "Rubicon Research", "symbol": "RUBICON", "segment": "NSE", "legal_name": "Rubicon Research Limited"},
    {"name": "KSH International", "symbol": "KSHINTL", "segment": "NSE SME"},
    {
        "name": "Groww",
        "symbol": "GROWW",
        "segment": "NSE",
        "legal_name": "Billionbrains Garage Ventures Limited",
    },
    {"name": "Corona Remedies", "symbol": "CORONA", "segment": "NSE"},
    {"name": "Aequs", "symbol": "AEQUS", "segment": "NSE"},
    {"name": "Park Medi World", "symbol": "PARKHOSPS", "segment": "NSE SME"},
    {"name": "Vidya Wires", "symbol": "VIDYAWIRES", "segment": "NSE"},
    {"name": "Fujiyama Power Systems", "symbol": "UTLSOLAR", "segment": "NSE"},
    {"name": "Meesho", "symbol": "MEESHO", "segment": "NSE"},
    {"name": "Emmvee Photovoltaic Power", "symbol": "EMMVEE", "segment": "NSE"},
    {"name": "Jain Resource Recycling", "symbol": "JAINREC", "segment": "NSE"},
    {"name": "Nephrocare Health Services", "symbol": "NEPHROPLUS", "segment": "NSE"},
    {
        "name": "ICICI Prudential AMC",
        "symbol": "ICICIAMC",
        "segment": "NSE",
        "legal_name": "ICICI Prudential Asset Management Company Limited",
    },
    {"name": "Sudeep Pharma", "symbol": "SUDEEPPHRM", "segment": "NSE"},
    {"name": "Canara HSBC Life Insurance Co", "symbol": "CANHLIFE", "segment": "NSE"},
    {"name": "Tenneco Clean Air India", "symbol": "TENNIND", "segment": "NSE"},
    {"name": "LG Electronics India", "symbol": "LGEINDIA", "segment": "NSE"},
    {"name": "Epack Prefab Technologies", "symbol": "EPACKPEB", "segment": "NSE"},
    {"name": "PhysicsWallah", "symbol": "PWL", "segment": "NSE"},
    {"name": "Midwest", "symbol": "MIDWESTLTD", "segment": "NSE"},
    {"name": "Gujarat Kidney & Super Speciality", "symbol": "GKSL", "segment": "NSE SME"},
    {"name": "Advance Agrolife", "symbol": "ADVANCE", "segment": "NSE"},
    {"name": "WeWork India Management", "symbol": "WEWORK", "segment": "NSE"},
    {"name": "Tata Capital", "symbol": "TATACAP", "segment": "NSE"},
    {"name": "Dhara Rail Projects", "symbol": "DHARARAIL", "segment": "NSE SME"},
]
